server:
  port: 4000

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: ucmc-service

idam:
  s2s-auth:
    microservice: ucmc-service
