server:
  port: 4000

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: ucmc-service

fees:
  api:
    service: civil money claims
    jurisdiction1: civil
    jurisdiction2: county court
    channel: default
    event: issue

payments:
  api:
    # TODO: update once f&p onboarding is completed
    site_id:
    service:

idam:
  s2s-auth:
    microservice: ucmc_service

---

spring:
  profiles: local

fees:
  api:
    url: http://localhost:8765

payments:
  api:
    url: http://localhost:8765

idam:
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
  client:
    id: ucmc
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

---

spring:
  profiles: integration-test

fees:
  api:
    url: http://fake-fees-register-api

payments:
  api:
    url: http://fake-payment-register-api

idam:
  api:
    url: http://fake-idam-api
  s2s-auth:
    url: http://fake-service-auth-provider-api
    totp_secret: AABBCCDDEEFFGGHH
