server:
  port: 4000

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: ucmc-service

doc_assembly:
  url: ${DOC_ASSEMBLY_URL:false}
  sealedClaimTemplateId: "CV-CMC-GOR-ENG-0001.docx"

idam:
  s2s-auth:
    microservice: ucmc-service
