server:
  port: 4000

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: unspec-service
  cache:
    cache-names: userInfoCache
    caffeine:
      spec: expireAfterAccess=3600s
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${CMC_DB_USERNAME:-}
    password: ${CMC_DB_PASSWORD:-}
    url: jdbc:postgresql://${CMC_DB_HOST:}:${CMC_DB_PORT:}/${CMC_DB_NAME:cmc}${CMC_DB_CONNECTION_OPTIONS:}

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${idam.web.url}/o
        registration:
          oidc:
            client-id: internal
            client-secret: internal

oidc:
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

fees:
  api:
    service: civil money claims
    jurisdiction1: civil
    jurisdiction2: county court
    channel: default
    event: issue

payments:
  api:
    # TODO: update once f&p onboarding is completed
    site_id:
    service:

idam:
  s2s-auth:
    microservice: unspec-service

unspecified:
  response-pack-url: https://formfinder.hmctsformfinder.justice.gov.uk/n9-eng.pdf
  system-update:
    username: 'civil-system-update@mailnesia.com'
    password: 'Password12'

core_case_data:
  api:
    url: http://localhost:4452
reference:
  database:
    enabled: true

---

spring:
  profiles: local

fees:
  api:
    url: http://localhost:8765

payments:
  api:
    url: http://localhost:8765

idam:
  web:
    url: http://localhost:9002
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
  client:
    id: unspec
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

---

spring:
  profiles: integration-test
  main:
    lazy-initialization: true

management:
  endpoints:
    enabled-by-default: false

fees:
  api:
    url: http://fake-fees-register-api

payments:
  api:
    url: http://fake-payment-register-api

idam:
  web:
    url: http://fake-idam-web
  api:
    url: http://fake-idam-api
  s2s-auth:
    url: http://fake-service-auth-provider-api
    totp_secret: AABBCCDDEEFFGGHH

core_case_data:
  api:
    url: http://fake-ccd-data-store-api

reference:
  database:
    enabled: false
